Repository LT-Students/DigitalOffice-frontend, pull requests merged in 2021-08, with the labels that each got.

#170 Fix services dependencies
  src/app/app.module.ts
  src/app/core/models/user/user-status.model.ts
  src/app/core/services/attendance.service.ts
  src/app/core/services/auth/auth.service.ts
  src/app/core/services/user/user.service.ts
  src/app/data/store/project.store.ts
  src/app/modules/admin/components/new-project/new-project.component.ts
  src/app/modules/admin/modals/new-employee/new-employee.component.html
  src/app/modules/employee/components/main-info/main-info.component.ts
  src/app/modules/employee/components/projects/projects.component.ts
  src/app/modules/employee/employee-page.component.html
  src/app/modules/employee/employee-page.component.ts
  src/app/modules/user/components/attendance/attendance.component.ts
Labels: dependencies

#172 Add no whitespaces validator
  src/app/core/validators/do-validators.ts
  src/app/modules/admin/modals/new-employee/new-employee.component.html
  src/app/modules/admin/modals/new-employee/new-employee.component.ts
Labels: bug

#173 Trim login
  src/app/modules/auth/components/login/login.component.html
  src/app/modules/auth/components/login/login.component.ts
Labels: bug

#174 Add cancel button and refactor html
  src/app/modules/admin/modals/new-department/new-department.component.html
  src/app/modules/admin/modals/new-office/new-office.component.html
  src/app/modules/admin/modals/new-position/new-position.component.html
  src/app/modules/admin/modals/new-role/new-role.component.html
Labels: bug

#158 Feature/time project list
  src/app/core/services/time/time.service.ts
  src/app/data/store/project.store.ts
  src/app/modules/admin/components/manage-users/manage-users.component.ts
  src/app/modules/user/components/add-hours/add-hours.component.html
  src/app/modules/user/components/attendance/attendance.component.html
  src/app/modules/user/components/attendance/attendance.component.ts
  src/app/modules/user/components/comment/comment.component.html
  src/app/modules/user/components/comment/comment.component.scss
  src/app/modules/user/components/comment/comment.component.ts
  src/app/modules/user/components/leaves/leaves.component.html
  src/app/modules/user/components/leaves/leaves.component.scss
  src/app/modules/user/components/leaves/leaves.component.ts
  src/app/modules/user/components/project/project.component.html
  src/app/modules/user/components/project/project.component.scss
  src/app/modules/user/components/project/project.component.ts
  src/app/modules/user/components/projects-table/projects-table.component.ts
  src/app/modules/user/components/projects/projects.component.html
  src/app/modules/user/components/projects/projects.component.scss
  src/app/modules/user/components/projects/projects.component.spec.ts
  src/app/modules/user/components/projects/projects.component.ts
  src/app/modules/user/components/user-tasks/user-tasks.component.html
  src/app/modules/user/components/user-tasks/user-tasks.component.scss
  src/app/modules/user/components/user-tasks/user-tasks.component.ts
  src/app/modules/user/modals/delete-leave/delete-leave.component.html
  src/app/modules/user/modals/delete-leave/delete-leave.component.scss
  src/app/modules/user/modals/delete-leave/delete-leave.component.ts
  src/app/modules/user/modals/edit-leave/edit-leave.component.html
  src/app/modules/user/modals/edit-leave/edit-leave.component.scss
  src/app/modules/user/modals/edit-leave/edit-leave.component.ts
  src/app/modules/user/modals/edit-project/edit-project.component.html
  src/app/modules/user/modals/edit-project/edit-project.component.scss
  src/app/modules/user/modals/edit-project/edit-project.component.ts
  src/app/modules/user/user.module.ts
  src/styles.scss
  src/stylesheets/layouts/_table.scss
Labels: enhancement

#169 Improvement/datapicker
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/core/core.module.ts
  src/app/core/services/attendance.service.ts
  src/app/core/services/date.service.ts
  src/app/core/services/user/user.service.ts
  src/app/modules/employee/components/main-info/main-info.component.ts
  src/app/modules/user/components/add-hours/add-hours.component.html
  src/app/modules/user/components/add-hours/add-hours.component.ts
  src/app/modules/user/components/attendance/attendance.component.html
  src/app/modules/user/components/attendance/attendance.component.scss
  src/app/modules/user/components/attendance/attendance.component.ts
  src/app/modules/user/components/chart/doughnut-chart.component.html
  src/app/modules/user/components/chart/doughnut-chart.component.scss
  src/app/modules/user/components/chart/doughnut-chart.component.ts
  src/app/modules/user/components/date-desc/date-desc.component.html
  src/app/modules/user/components/leaves/leaves.component.html
  src/app/modules/user/components/leaves/leaves.component.ts
  src/app/modules/user/components/projects/projects.component.html
  src/app/modules/user/components/projects/projects.component.ts
  src/app/modules/user/components/time-widget/doughnut-chart/doughnut-chart.component.html
  src/app/modules/user/components/time-widget/doughnut-chart/doughnut-chart.component.scss
  src/app/modules/user/components/time-widget/doughnut-chart/doughnut-chart.component.spec.ts
  src/app/modules/user/components/time-widget/doughnut-chart/doughnut-chart.component.ts
  src/app/modules/user/components/time-widget/time-widget.component.html
  src/app/modules/user/components/time-widget/time-widget.component.scss
  src/app/modules/user/components/time-widget/time-widget.component.spec.ts
  src/app/modules/user/components/time-widget/time-widget.component.ts
  src/app/modules/user/components/user-tasks/user-tasks.component.html
  src/app/modules/user/components/user-tasks/user-tasks.component.ts
  src/app/modules/user/modals/delete-leave/delete-leave.component.ts
  src/app/modules/user/modals/edit-leave/edit-leave.component.html
  src/app/modules/user/modals/edit-leave/edit-leave.component.ts
  src/app/modules/user/modals/edit-project/edit-project.component.ts
  src/app/modules/user/user.module.ts
  src/app/shared/component/header/header.component.html
  src/assets/images/Arrow right.png
  src/assets/images/ArrowLeft.png
  src/assets/images/ArrowRight.png
  src/assets/images/Ellipse 216.png
  src/assets/images/Vector 50.png
  src/index.html
  src/stylesheets/base/_variables.scss
Labels: enhancement
